### ISSUE TITLE
On Windows, the panel cannot be superimposed on Browser and Legend panels

### ISSUE THREAD

**Issue by pcav** [enricofer/go2streetview#12]
On Linux it works smoothly.

**Comment by enricofer** [comment]
do you mean it throws exceptions or it is glued to the left dockwidget? In the second case I think it is the right behaviour, perhaps it depends from the cursor drag point in the dialog caption. In the first case I need more infos to replicate issue because I don't find any issue on my windows system:
![clipboard01](https://cloud.githubusercontent.com/assets/7544963/8034146/53064c94-0de5-11e5-88bb-a485a457ef03.png)
![clipboard02](https://cloud.githubusercontent.com/assets/7544963/8034147/5306fff4-0de5-11e5-811e-6a4960b1a006.png)

**Comment by pcav** [comment]
It is gliued, ad this is OK, but the problem is that it does not allow to overlap Browser and Layer panels, as tabbed ones, nor resizing them.
Thanks.

**Comment by enricofer** [comment]
fixed. 
https://github.com/enricofer/go2streetview/commit/dcbdb40c6c7445f6dc5580f438ffa7527df1618c
