### ISSUE TITLE
SSL error when trying to view streetview

### ISSUE THREAD

**Issue by EdRollason** [enricofer/go2streetview#26]
When activating the plugin and clicking on the map I am getting an SSL error like the one attached.  Clicking ignore just results in a black screen.  

![image](https://cloud.githubusercontent.com/assets/7903405/20532751/f985ce8c-b0d2-11e6-8920-455cb1dd4a81.png)

Using plugin version 7.0 

QGIS version: 2.16.2 -> Kyng Chaos Installation
QGIS code branch: Release 2.16
Compiled against Qt 4.8.6
Running against Qt 4.8.6
Compiled against GDAL/OGR 2.1.1
Running against GDAL/OGR 2.1.1
Compiled against GEOS 3.5.0-CAPI-1.9.0
Running against GEOS 3.5.0-CAPI-1.9.0 r0
PostgreSQL Client Version 9.4.4
SpatiaLite Version 4.3.0a
QWT Version 6.1.3
PROJ.4 Version 492
QScintilla2 Version 2.9.3

Running on Max OSX Sierra Version 10.12.1

**Comment by enricofer** [comment]
from Carlo A. Nicolini <t4950c@gmail.com> 
Buongiorno,
Chiedo scusa per il disturbo, ho un problema che mi assilla da un po di tempo e non riesco a trovare soluzione…. Causa mia ignoranza, sia informatica che di lingua (inglese.. a livello scolastico, asilo)
… mi vengono fuori errori in serie relativamente alle API di google… il problema si propone sia su Mac OS X sierra … personale, che su pc win 7 64 bit in rete aziendale in ufficio…


.. questo è il primo avviso

https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=26.16&action=apiboot2&rt=main.8

* Unable To Get Local Issuer Certificate: The issuer certificate of a locally looked up certificate could not be found
* Certificate Untrusted: The root CA certificate is not trusted for this purpose

… e continua con schermate continue…… per poi visualizzare le immagini..

Puoi aiutarmi in qualche modo.?

Grazie in anticipo e anche per il plugin
Saluti

**Comment by enricofer** [comment]
Could you check the new [master version](https://github.com/enricofer/go2streetview/archive/master.zip) inserting [Google Maps API key](https://github.com/enricofer/go2streetview/wiki/Release-7.2---Insert-Google-Maps-API-key) and report if the issue remains?

**Comment by takezo39** [comment]
Hello, I have the same issue. Do I understand correctly that I would need QGIS 3 to run plugin master? If so, I don't think I can solve this issue without trying to install QGIS without the Kyng Chaos installation, since latest kyng choas is 2.18.9.

![screen shot 2018-02-15 at 12 15 23](https://user-images.githubusercontent.com/18402307/36254339-14e33d10-124b-11e8-9557-c377db769f83.png)


Using plugin version 7.5
QGIS version: 2.18.9 -> Kyng Chaos Installation
QGIS code branch | Release 2.18
Compiled against Qt | 4.8.6 
Running against Qt | 4.8.6
Compiled against GDAL/OGR | 2.1.3 
Running against GDAL/OGR | 2.1.3
Compiled against GEOS | 3.6.1-CAPI-1.10.1 
Running against GEOS | 3.6.1-CAPI-1.10.1 r0
PostgreSQL Client Version | 9.3.4 
SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | 
PROJ.4 Version | 492
QScintilla2 Version | 2.9.3 

macOS Sierra 10.12.6
