### ISSUE TITLE
QGIS 3.4 - Extension disabled because it caused QGIS to crash

### ISSUE THREAD

**Issue by Fabien98** [enricofer/go2streetview#41]
Hello, I just freshly installed the new QGIS 3.4 but I encountered an error with this plugin.

When I activate the plugin I have a Window pop-up error which states:

> This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above)

It seems that this issue is related to a pyQT5 version.. (see [related issue](https://github.com/winpython/winpython/issues/592) here)

**Comment by zezzagio** [comment]
I didn't do extensive testing, but simply deleting Qt from the import list of PyQt5 seems to fix the problem.

I don't think go2streetview should need the Bluetooth API. I better fix is expected from the author, or from the PyQt5 team, though.

Ciao.

**Comment by Fabien98** [comment]
I created a bug report on the QGIS bugtracker:
https://issues.qgis.org/issues/20867

**Comment by zezzagio** [comment]
A plugin should not be able to block the application, for any reason; this is definitely an application bug, in my opinion; in principle, at least

The plugin, though, should get rid of unwanted, and unneeded dependencies. At least, it can, when they are creating problem like in this case.

Instead of the generic "import Qt", which import all (and thus Blutooth, of which I dind't find any reference in the rest of the code) I suggest using more specific imports; all the more because they are already here: it says "import Qt", and then it goes ahead and says "and I mean: QtCore, QtWidgets, QtGui, QtWebKit..." At this point, it seems just natural to me to delete the generic import, and stay with and only with what is needed.

Ciao.

**Comment by Fabien98** [comment]
QGIS rejected my bug report and made the same conclusion that @zezzagio .
Thanks for your input by the way.

> Status changed from Open to Rejected
> Resolution set to up/downstream
> 
> Please file bugreport in the plugin bugtracker, as QGIS itself does not requires Bluetooth. Seems that in the plugin code there is a incorrect import.
